# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install 💾
        run: npm ci

      - name: Build Node Version
        run: npm build

      - name: Build Browser Version
        run: npm build:browser

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

